openapi: "3.0.2"
info:
  title: Mintcraft Gateway API
  version: "0.1.0"
servers:
  - url: https://api.server.test/v0
paths:
  /test:
    get:
      responses:
        "200":
          description: OK
